### ISSUE TITLE
App built from github is block in start screen

### ISSUE THREAD

**Issue by dynatom** [mattermost/mattermost-mobile#2303]
#### Summary
App built from github is not working.

#### Environment Information

- Device Name: Samsung Galaxy A5
- OS Version: Android 8.0.0, Samsung Experience 9.0, Knox 3.1, Knox API 25, TIMA 3.3.0
- Mattermost App Version: Github master branch
- Mattermost Server Version: Mattermost Enterprise Edition

#### Steps to reproduce
Launch the app after build with following step.

1.Get code from [github](https://github.com/mattermost/mattermost-mobile) master branch

2.environments:
`export id1=com.dyna.mattermosta
export id2=$id1.MattermostShare
export VERSION_NUMBER=1.0.2
export BUILD_NUMBER=2
export APP_NAME="DynaMattermostA"
export MAIN_APP_IDENTIFIER=$id1
export SUPPLY_PACKAGE_NAME=$id1
export EXTENSION_APP_IDENTIFIER=$id2`

3.Replace android\app\google-services.json with [google-services.json](https://drive.google.com/file/d/14HxSVvBynTjVCgtRVdcIqpwWZO6pSn4y/view?usp=sharing)

4.Add these to android\app\build.gradle
`dependencies {
    implementation 'com.google.firebase:firebase-core:16.0.1'
}
//bottom of the file
apply plugin: 'com.google.gms.google-services'`

5.Change value with google-services.json to android\app\src\main\AndroidManifest.xml
`<meta-data android:name="com.wix.reactnativenotifications.gcmSenderId" android:value="563680424932\"/>`

6.Copy assets\base\config.json to assets\override\config.json and change value
`"DefaultServerUrl": "http://35.194.214.80:8066",
"AutoSelectServerUrl": true,`

7.In mac console, use `make build-android && make run-android`
Mac Information:
macOS High Sierra
version 10.13.6 (17G65)
Mac mini (Mid 2011)

#### Expected behavior
After launch the app.
It always stay in this [screen](https://imgur.com/747q4aR).

#### Observed behavior
In the adb [logcat.](https://drive.google.com/file/d/108_FV5_FkZ_M5r1QQgAKTW-3GBIWcS-1/view?usp=sharing)
I found this error with ReactNative.
`2018-10-31 14:07:50.428 22780-23537/com.dyna.mattermosta E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:216)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:243)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1114)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:913)
        at java.lang.Thread.run(Thread.java:764)
2018-10-31 14:07:50.434 22780-22780/com.dyna.mattermosta E/unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.`

At another [test](https://drive.google.com/file/d/1Cww0-c-n4_0N6qZ5w2-d0fnVaFWZ_Xjn/view?usp=sharing)
`10-29 14:01:33.694 18148 18148 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbp;
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6578)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
10-29 14:01:33.694 18148 18148 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by dynatom** [comment]
I also tried not use environments.
Just git pull and change google-services.json.
Then make build & run, but it also block in the same startscreen.

**Comment by amyblais** [comment]
@enahum ^

**Comment by enahum** [comment]
1. Why are you adding `implementation 'com.google.firebase:firebase-core:16.0.1'` on step 3 ?
2. on 5 you only need to have the values that you want to override

why are you running make build-android and make run-android?

build is used to compile the app and get the apk, run is to compile the app and run it in dev mode.

Also when building the app make sure your the react-native packager is running without issues. you can test that by executing **make start** check that everything works fine and then try again

**Comment by enahum** [comment]
Your step 3 is not needed, please make sure to follow the guide [here](https://developers.mattermost.com/contribute/mobile/build-your-own/)

**Comment by enahum** [comment]
Looks like you afe trying to build with node 11? Try node 9 or 10

**Comment by shawn111** [comment]
I trird below node & npm.
node v8.12.0 / npm v6.4.1
node v9.11.2 / npm v5.6.0
node v10.13.0 / npm v6.4.1
node v11.1.0 / npm v6.4.1

The error messages show as below.

```
> Task :app:bundleReleaseJsAndAssets                                                                                                                           
warning: the transform cache was reset.                                                                                                                        
Loading dependency graph, done.                                                                                                                                
BUILDING MODULES FOR android                                                                                                                                   
                                                                                                                                                               
Unable to resolve module `mattermost-redux/utils/event_emitter` from `/root/mattermost-mobile/app/mattermost.js`: Module `mattermost-redux/utils/event_emitter` does not exist in the Haste module map     
```

**Comment by dynatom** [comment]
I try nvm to install 9.3.0 which [Developer Setup suggests](https://developers.mattermost.com/contribute/mobile/developer-setup/)

> $ node --version
> v9.3.0
> $ npm --version
> 5.5.1

but still see the error

> error: bundling failed: Error: Unable to resolve module `mattermost-redux/utils/event_emitter` from `/Users/rd620/Desktop/mattermost-mobile/app/mattermost.js`: Module `mattermost-redux/utils/event_emitter` does not exist in the Haste module map

It seems because of the path error of mattermost-redux.
Find the node_modules folder, `mattermost-redux/utils/event_emitter` doesn't exist but `mattermost-redux/src/utils/event_emitter` exists.

**Comment by enahum** [comment]
It seems that somehow in your setup the mattermost-redux library is not building properly.

Try changing directory to `node_modules/mattermost-redux` then run `npm install` and `npm run build` before building the app.

Then we can try why mattermost-redux is not being installed properly in your environment

**Comment by dynatom** [comment]
Use `make build-android`

> cd mattermost-mobile
> rm -f -r node_modules
> npm install
> cd node_modules/mattermost-redux
> npm install
> npm run build
> make build-android

[Result](https://imgur.com/LbW93QB)
Seems node9.3.0/npm5.5.1 don't support `npm ci`

> npm install npm@5.7 -g
> make build-android

Use .apk install app, still block in start screen (no local:8081 to connect).


Use  `make run-android`

> cd mattermost-mobile
> rm -f -r node_modules
> npm install
> cd node_modules/mattermost-redux
> npm install
> npm run build
> make run-android

[Succes](https://imgur.com/UdZmjif)
It finally passes the start screen.
But needs connect mac and phone.

Try `VARIANT=release make run-android`
[Build failed](https://imgur.com/LgiJ8Wb)
Any extra setting when build release?

**Comment by dynatom** [comment]
> I'm using node v10.11.0 and npm 6.4.1 and is working fine for me.
> 
> ```
> cd mattermost-mobile
> make clean
> source ~/mattermost-mobile-env-vars
> make build-android
> ```
> my `mattermost-mobile-env-vars` file for building android only
> 
> ```
> export LC_ALL="en_US.UTF-8"
> export NODE_OPTIONS=--max_old_space_size=12000
> 
> ############ MATTERMOST BUILD ############
> export COMMIT_CHANGES_TO_GIT=true
> export BRANCH_TO_BUILD=master
> export GIT_LOCAL_BRANCH=build
> export RESET_GIT_BRANCH=true
> 
> export APP_NAME=Mattermost
> #export VERSION_NUMBER=1.13.0
> #export BUILD_NUMBER=144
> export BETA_BUILD=false
> export BUILD_FOR_RELEASE=true
> export REPLACE_ASSETS=true
> 
> export MAIN_APP_IDENTIFIER=com.mattermost.rn
> export EXTENSION_APP_IDENTIFIER=com.mattermost.rn.MattermostShare
> ```

Thanks.

Use only two env, can build debug, can't build release.
> export APP_NAME="DynaMattermostA"
> export MAIN_APP_IDENTIFIER=com.dyna.mattermosta

I go to try these and build release again.

> export NODE_OPTIONS=--max_old_space_size=12000
> export COMMIT_CHANGES_TO_GIT=true
> export BRANCH_TO_BUILD=master
> export GIT_LOCAL_BRANCH=build
> export RESET_GIT_BRANCH=true
> export BETA_BUILD=false
> export BUILD_FOR_RELEASE=true
> export REPLACE_ASSETS=true

**Comment by dynatom** [comment]
Thanks all a lot.
Finally build release success.
The enviorment needs these two for building release apk.
> export BUILD_FOR_RELEASE=true
> export BETA_BUILD=false

If no `BETA_BUILD=false` would build release error.

**Comment by sushantbansal90** [comment]
i have same problem but unable to find location of (mattermost-mobile-env-vars) file

**Comment by enahum** [comment]
@sushantbansal90 here is the file https://github.com/mattermost/mattermost-mobile/blob/614e8e32ca1caf13ae3a04d97b95458a05ad6347/fastlane/env_vars_example you can also refer to the docs here https://developers.mattermost.com/contribute/mobile/build-your-own/
