### ISSUE TITLE
Mattermost mobile release build (signed) in android crashes on launch 

### ISSUE THREAD

**Issue by P-r-a-d-e-e-P** [mattermost/mattermost-mobile#2757]
#### Summary
Mattermost mobile app crashes when run using release mode with signed build. App works fine in dev mode and in debug mode.

#### Environment Information

- Device Name: Lava Iris 60
- OS Version: Android 7.0 API 24
- Mattermost App Version: 1.18.1
- Mattermost Server Version: Screen for server link is not showing itself.

#### Steps to reproduce
Followed instructions on https://developers.mattermost.com/contribute/mobile/developer-setup/ and https://developers.mattermost.com/contribute/mobile/build-your-own/ to setup

Setup Fastlane and Environment variables.

Build for android and Installed the apk to real device using "adb install" command. 
Started the app in device.  

I'm new to mattermost and react native in general. Kindly support.

#### Expected behavior
App should run as it does in debug and dev mode.

#### Observed behavior

App crashes and logs shows the below error:

2019-05-01 13:01:48.892 348-663/? E/AudioFlinger: getNextBuffer, track(0xb43e2900) get null buffer, mState 6, mFillingUpStatus 2
2019-05-01 13:01:49.571 979-1304/? E/LavaAppLockService: openAppLock pkgName:com.mattermost.rnbeta
2019-05-01 13:01:53.992 236-554/? E/MAL-RDS:  (  rds_ru_3gpp_status_ind, 1616) [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x8
2019-05-01 13:01:54.149 5977-5977/? E/chromium: [ERROR:filesystem_posix.cc(89)] stat /data/user/0/com.mattermost.rnbeta/cache/WebView/Crashpad: No such file or directory (2)
2019-05-01 13:01:54.150 5977-5977/? E/chromium: [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/com.mattermost.rnbeta/cache/WebView/Crashpad: No such file or directory (2)
2019-05-01 13:01:54.264 5977-6016/? E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
2019-05-01 13:01:55.358 5977-6016/? E/RNKeychainManager: No entry found for service: 
2019-05-01 13:01:55.547 5977-6016/? E/ReactNativeJS: Requiring module "412", which threw an exception: TypeError: r(d[2]) is not a function. (In 'r(d[2])(this)', 'r(d[2])' is an instance of Object)
    
    --------- beginning of crash
2019-05-01 13:01:55.583 5977-6017/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.mattermost.rnbeta, PID: 5977
    com.facebook.react.common.JavascriptException: Requiring module "412", which threw an exception: TypeError: r(d[2]) is not a function. (In 'r(d[2])(this)', 'r(d[2])' is an instance of Object), stack:
    _@2:1338
    <unknown>@411.js:1:140
    Wo@676.js:1:39260
    fu@676.js:1:20313
    fa@676.js:1:46716
    xu@676.js:1:21974
    co@676.js:1:36031
    n@676.js:1:13519
    <unknown>@676.js:1:72452
    <unknown>@676.js:1:72610
    _@2:1501
    <unknown>@661.js:1:224
    _@2:1501
    <unknown>@989.js:1:150
    _@2:1501
    <unknown>@360.js:1:357
    _@2:1501
    <unknown>@1.js:1:46
    _@2:1501
    d@2:884
    global code@12:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:203)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:761)
2019-05-01 13:01:55.754 979-1049/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=440, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
2019-05-01 13:01:55.817 979-1342/? E/LavaAppLockService: openAppLock pkgName:com.android.launcher3
2019-05-01 13:01:55.994 979-1045/? E/WifiStateMachine: mIsFullScanOngoing: false, mSendScanResultsBroadcast: false
2019-05-01 13:01:56.001 979-1047/? E/WifiScanningService: WifiSingleScanStateMachine IdleState enter
2019-05-01 13:01:59.107 236-554/? E/MAL-RDS:  (  rds_ru_3gpp_status_ind, 1616) [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x8
2019-05-01 13:02:04.244 236-554/? E/MAL-RDS:  (  rds_ru_3gpp_status_ind, 1616) [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x8
2019-05-01 13:02:04.377 979-1049/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=439, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
2019-05-01 13:02:05.027 236-580/? E/MAL-SIMMNGR:  ( simmngr_task_notify_hdl, 3461) 3461 EN_SIM:EVENT_MDMNGR_ATURC_NOTIFY: an unknown type : 0
2019-05-01 13:02:09.724 236-554/? E/MAL-RDS:  (  rds_ru_3gpp_status_ind, 1616) [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x8

**Comment by amyblais** [comment]
@svelle Are you familiar with this error?

**Comment by svelle** [comment]
No haven't seen it yet.

**Comment by enahum** [comment]
What branch are you trying to build?

**Comment by P-r-a-d-e-e-P** [comment]
@enahum : I was trying with the Master branch code.

**Comment by cburn11** [comment]
Sounds like https://github.com/mattermost/mattermost-mobile/issues/2729

**Comment by varungupta85** [comment]
Hi, I am not using mattermost but I am observing a similar error in my app only in release mode on Android after I moved my mobile app to a mono-repo structure. I would be grateful if you could share any information how to debug/fix this problem.
