### ISSUE TITLE
Android app crashes on launch after increasing targetSdkVersion to 28

### ISSUE THREAD

**Issue by zgordan-vv** [mattermost/mattermost-mobile#3292]
#### Summary
Android app crashes on launch after increasing targetSdkVersion to 28

#### Environment Information

- Device Name: Nexus 5X API 28 (Simulator)
- OS Version: 9
- Mattermost App Version: 1.21.0
- Mattermost Server Version: ?

#### Steps to reproduce
Change targetSdkVersion to 28 instead of 26 in android/build.gradle

#### Expected behavior
All runs ok

#### Observed behavior
in adb logcat e:*

E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
09-20 17:37:00.643 21489 21489 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
09-20 17:37:00.643 21489 21489 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-20 17:37:00.643 21489 21489 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
09-20 17:37:00.643 21489 21489 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-20 17:37:00.643 21489 21489 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-20 17:37:00.643 21489 21489 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-20 17:37:00.643 21489 21489 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-20 17:37:00.716  2085  2252 E InputDispatcher: channel 'a563760 com.xhq.tafe/com.xhq.tafe.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

#### Possible fixes
actually the issue is caused by startGcmIntentService method in node_modules/react-native-notifications/android/src/main/java/com/wix/reactnativenotifications/RNNotificationsModule.java , but I have no idea how to handle it

**Comment by zgordan-vv** [comment]
I see it is fixed in df3a3eb3
