### ISSUE TITLE
Unable to run code

### ISSUE THREAD

**Issue by rishabhshah09** [mattermost/mattermost-mobile#3642]
Unable to run code getting below errors

error: bundling failed: Error: Unable to resolve module `./dist
/assets/config` from `index.js`: 

None of these files exist:
  * dist/assets/config(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * dist/assets/config/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/home/ubuntu/MatterMost/mattermost-mobile-master/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/home/ubuntu/MatterMost/mattermost-mobile-master/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/ubuntu/MatterMost/mattermost-mobile-master/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/home/ubuntu/MatterMost/mattermost-mobile-master/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /home/ubuntu/MatterMost/mattermost-mobile-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/home/ubuntu/MatterMost/mattermost-mobile-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /home/ubuntu/MatterMost/mattermost-mobile-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/ubuntu/MatterMost/mattermost-mobile-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

**Comment by enahum** [comment]
Does this happen if you follow the docs?

Anyway, you could run `make dist/assets`. The previous command should be implicitly called by `pre-run`, `start` or `build*`

**Comment by rishabhshah09** [comment]
Thanks, @enahum,

It is working
