### ISSUE TITLE
Android - Image can't be loaded, forcing the app to crash

### ISSUE THREAD

**Issue by malmstein** [mattermost/mattermost-mobile#4310]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Entering a channel with an image makes the application crash

#### Environment Information

This is my device's information, although it crashes for everyone else on the team.

- Device Name: Nexus 3a
- OS Version: Android 10
- Mattermost App Version: 1.31.0
- Mattermost Server Version:

#### Steps to reproduce
Add an image to a channel and try to open that channel from the Android app. Sadly this is as much as I can reproduce, the app is completely stuck for everyone on our team and can't really find the image that causes the issue.

#### Expected behavior
App should not crash

#### Observed behavior
```
2020-05-20 11:17:23.868 25979-25979/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mattermost.rn, PID: 25979
    java.lang.IllegalArgumentException: Must not be null or empty
        at com.bumptech.glide.util.Preconditions.checkNotEmpty(Preconditions.java:37)
        at com.bumptech.glide.load.model.GlideUrl.<init>(GlideUrl.java:56)
        at com.dylanvann.fastimage.FastImageSource.getGlideUrl(FastImageSource.java:110)
        at com.dylanvann.fastimage.FastImageViewModule$1.run(FastImageViewModule.java:48)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

[Link to Glide source](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/model/GlideUrl.java)

[Link to FastImage](https://github.com/DylanVann/react-native-fast-image/blob/master/android/src/main/java/com/dylanvann/fastimage/FastImageViewModule.java)

#### Possible fixes
Ensure that the image has a URL

**Comment by amyblais** [comment]
A ticket is open for this here: https://mattermost.atlassian.net/browse/MM-25347.

**Comment by enahum** [comment]
@malmstein could you share back the image?

**Comment by malmstein** [comment]
I was wrong @enahum, the app was crashing before that image was posted so I'm afraid I can't have the exact image that made it crash.
