### ISSUE TITLE
java.lang.NullPointerException in NavigationModule

### ISSUE THREAD

**Issue by liuan3756** [mattermost/mattermost-mobile#5888]
just launch app and go this
 java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter context
        at com.reactnativenavigation.options.params.ThemeColour$Companion.parse(Unknown Source:2)
        at com.reactnativenavigation.options.params.ThemeColour.parse(Unknown Source:2)
        at com.reactnativenavigation.options.TopBarBackgroundOptions.parse(TopBarBackgroundOptions.java:18)
        at com.reactnativenavigation.options.TopBarOptions.parse(TopBarOptions.java:34)
        at com.reactnativenavigation.options.Options.parse(Options.java:22)
        at com.reactnativenavigation.options.LayoutFactory.createComponent(LayoutFactory.java:164)
        at com.reactnativenavigation.options.LayoutFactory.create(LayoutFactory.java:78)
        at com.reactnativenavigation.options.LayoutFactory.createChildren(LayoutFactory.java:208)
        at com.reactnativenavigation.options.LayoutFactory.createStack(LayoutFactory.java:187)
        at com.reactnativenavigation.options.LayoutFactory.create(LayoutFactory.java:82)
        at com.reactnativenavigation.options.LayoutFactory.createSideMenuContent(LayoutFactory.java:145)
        at com.reactnativenavigation.options.LayoutFactory.create(LayoutFactory.java:88)
        at com.reactnativenavigation.options.LayoutFactory.createSideMenuRoot(LayoutFactory.java:113)
        at com.reactnativenavigation.options.LayoutFactory.create(LayoutFactory.java:86)
        at com.reactnativenavigation.react.NavigationModule.lambda$setRoot$0$NavigationModule(NavigationModule.java:125)
        at com.reactnativenavigation.react.-$$Lambda$NavigationModule$E_MipvwmSXbE6NbWJMzJlMGlDfk.run(Unknown Source:8)
        at com.reactnativenavigation.react.NavigationModule.lambda$handle$14$NavigationModule(NavigationModule.java:239)
        at com.reactnativenavigation.react.-$$Lambda$NavigationModule$sXUG5B2EQ5skHUFYfoWeiHKR6OE.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
        
![Screenshot_20211230_211859_com minerhub mattermost rnbeta](https://user-images.githubusercontent.com/23450706/147755958-f10a80cd-d4b5-4276-8deb-3b4917934277.jpg)

**Comment by amyblais** [comment]
@liuan3756 What Mattermost mobile app version are you on? What Mattermost server version are you on?

**Comment by liuan3756** [comment]
> @liuan3756 What Mattermost mobile app version are you on? What Mattermost server version are you on?

app source code from tag 1.48.1，server code from tag 6.0.0
