### ISSUE TITLE
Crash on Open with Self-compiled Android App

### ISSUE THREAD

**Issue by starlightknight** [mattermost/mattermost-mobile#6092]
#### Summary
Self-compiled v1.50.1 Android app succeeds on Linux but crashes immediately on open.

### Environment Information

  - Device Name: Android Emulator (happens on my real phone too)
  - OS Version: Built on Linux Mint 20.3, nvm use 16 (documentation says 15 or 16)
  - Mattermost App Version: 1.50.1
  - Mattermost Server Version: 6.4

#### Steps to reproduce

- I checked out the latest release tag (v1.50.1 at the time of writing)
- I followed the steps on the develop set up / building your own app pages in your documentation.
- Included my own google-services.json per the documentation for push messaging, but otherwise have no changes to the app.
- I built the android app with "npm run build:android" with BUILD_FOR_RELEASE=true in the fastlane/.env 
- Build was successful and APK was generated.
- After installing, the application crashes immediately on open.

#### Expected behavior

- App should work

#### Observed behavior (that appears unintentional)

App crashes immediately. The following message appears in logcat when the crash occurs. Looking inside the generated apk, this specific library is indeed not in the lib folder. Googling this error provides no helpful results.

```
    --------- beginning of crash
2022-03-26 19:05:13.118 4146-4193/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.mattermost.rnbeta, PID: 4146
    java.lang.UnsatisfiedLinkError: dlopen failed: library "librnmmkv.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.ammarahmed.mmkv.RNMMKVModule.<clinit>(RNMMKVModule.java:38)
        at com.ammarahmed.mmkv.RNMMKVPackage.createNativeModules(RNMMKVPackage.java:17)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1462)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1433)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1327)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1104)
        at java.lang.Thread.run(Thread.java:923)
```

#### Possible fixes

No idea. I haven't built the app in awhile, but I previously had built and used it successfully. The last time I built it was v1.2x

**Comment by starlightknight** [comment]
I tried compiling on Mac OS X today and the above mentioned library was properly included and the app worked. I have no idea why just that one lib is not present when I built on Linux.
