### ISSUE TITLE
File upload crash

### ISSUE THREAD

**Issue by kuon** [mattermost/mattermost-mobile#7033]
On android lineage 19-20221206 (android 12). App version 2.0.0.

If I try to upload a file (pdf), the file picker opens and the app crashes when a file is picked.

Here is the log

```
01-27 16:16:31.467 18027 18064 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-27 16:16:31.467 18027 18064 E AndroidRuntime: Process: com.mattermost.rn, PID: 18027
01-27 16:16:31.467 18027 18064 E AndroidRuntime: java.lang.NullPointerException: uri
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at java.util.Objects.requireNonNull(Objects.java:245)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1193)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at com.mattermost.helpers.RealPathUtil.getDataColumn(RealPathUtil.java:155)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at com.mattermost.helpers.RealPathUtil.getRealPathFromURI(RealPathUtil.java:73)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at com.mattermost.rn.MattermostManagedModule.getFilePath(MattermostManagedModule.java:126)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
01-27 16:16:31.467 18027 18064 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
01-27 16:16:31.481  1323  1394 I SDM     : HWDeviceDRM::UpdateMixerAttributes: Mixer WxH 1080x2520-0 for Peripheral
01-27 16:16:31.481  1323  1394 I SDM     : HWCDisplay::SubmitDisplayConfig: Active configuration changed to: 0
01-27 16:16:31.482  1528 18166 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-27 16:16:31.483  1528 26005 W ActivityTaskManager:   Force finishing activity com.mattermost.rn/.MainActivity

```

**Comment by amyblais** [comment]
We have a fix queued for this via https://github.com/mattermost/mattermost-mobile/pull/6984.
