### ISSUE TITLE
Android and iOS app crashes when trying to make or receive call

### ISSUE THREAD

**Issue by dominik59** [mattermost/mattermost-mobile#7155]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name: Oneplus 6T, iOS
  - OS Version: Android v13, IOS 16
  - Mattermost App Version: 2.1.0
  - Mattermost Server Version: 7.1,7.8

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Open app, login to server, try to call someone from the mobile app. When you start call from the app, and someone will receive a call from the web app - mobile app will crash but until i click X Close button on Android's Crash monit i can speak with remote person, but if i try to receive call on Android app it crashes.

#### Expected behavior
Describe your issue in detail
I should be able to receive call and make a call on Adroid app without App crashing

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages, screenshots and/or video recordings.
Application crashes and shut off.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

### Additional info:
It is common problem, all people in the team has got the same problem. We can call only on the web app.

### Logs
```
Logs from logcat:
2023-02-23 13:13:16.617 27255-27305/? I/TurboLogger: websocket connecting to wss://mattermost.xxxxx.app/api/v4/websocket
2023-02-23 13:13:16.863 27255-27305/? I/TurboLogger: websocket connected to wss://mattermost.xxxxx.app/api/v4/websocket
2023-02-23 13:13:24.703 27255-27264/? I/m.mattermost.rn: Background concurrent copying GC freed 1169838(44MB) AllocSpace objects, 123(3624KB) LOS objects, 75% free, 14MB/56MB, paused 91us,53us total 171.568ms
2023-02-23 13:13:26.574 1235-4565/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10262/27255 AA=USAGE_VOICE_COMMUNICATION/CONTENT_TYPE_SPEECH clientId=android.media.AudioManager@51762d1com.zxcpoiu.incallmanager.InCallManagerModule@d2b81a4 callingPack=com.mattermost.rn req=2 flags=0x0 sdk=33
2023-02-23 13:13:26.676 27255-27305/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.mattermost.rn, PID: 27255
    com.facebook.react.bridge.NoSuchKeyException: dispatchEvent
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:110)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:114)
        at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:146)
        at com.mattermostreactnativeturbolog.Helpers.convertMapToJson(Helpers.java:21)
        at com.mattermostreactnativeturbolog.ReactNativeTurboLogModuleImpl.format(ReactNativeTurboLogModuleImpl.java:188)
        at com.mattermostreactnativeturbolog.ReactNativeTurboLogModuleImpl.write(ReactNativeTurboLogModuleImpl.java:111)
        at com.mattermostreactnativeturbolog.ReactNativeTurboLogModule.write(ReactNativeTurboLogModule.java:33)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:1012)
2023-02-23 13:13:26.687 1235-4565/? W/ActivityTaskManager:   Force finishing activity com.mattermost.rn/.MainActivity
2023-02-23 13:13:26.705 1235-1501/? I/ActivityManager: Showing crash dialog for package com.mattermost.rn u0
2023-02-23 13:13:26.741 1235-1501/? D/CoreBackPreview: Window{595d730 u0 Application Error: com.mattermost.rn}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@c4f26eb, mPriority=0}
2023-02-23 13:13:27.344 1235-2029/? D/CoreBackPreview: Window{e64778d u0 com.mattermost.rn/com.mattermost.rn.MainActivity}: Setting back callback null
2023-02-23 13:13:27.347 1235-2029/? W/InputManager-JNI: Input channel object 'e64778d com.mattermost.rn/com.mattermost.rn.MainActivity (client)' was disposed without first being removed with the input manager!
2023-02-23 13:13:27.385 1235-1529/? W/BroadcastQueue: Skipping deliver [background] BroadcastRecord{cf91597 u-1 android.intent.action.BATTERY_CHANGED} to ReceiverList{1e9533 27255 com.mattermost.rn/10262/u0 remote:75954a2}: process gone or crashing
2023-02-23 13:13:30.898 1235-1529/? W/BroadcastQueue: Skipping deliver [background] BroadcastRecord{6cdc3ee u-1 android.intent.action.BATTERY_CHANGED} to ReceiverList{1e9533 27255 com.mattermost.rn/10262/u0 remote:75954a2}: process gone or crashing
2023-02-23 13:13:33.792 1235-1529/? W/BroadcastQueue: Skipping deliver [background] BroadcastRecord{f63208f u-1 android.intent.action.BATTERY_CHANGED} to ReceiverList{1e9533 27255 com.mattermost.rn/10262/u0 remote:75954a2}: process gone or crashing
2023-02-23 13:13:35.560 1235-1501/? D/CoreBackPreview: Window{595d730 u0 Application Error: com.mattermost.rn}: Setting back callback null
2023-02-23 13:13:35.567 1235-1501/? W/InputManager-JNI: Input channel object '595d730 Application Error: com.mattermost.rn (client)' was disposed without first being removed with the input manager!
2023-02-23 13:13:35.649 1235-3946/? I/ActivityManager: Process com.mattermost.rn (pid 27255) has died: cch CRE 
2023-02-23 13:13:35.650 1235-4586/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10262/27255, [NetworkRequest [ LISTEN id=9470, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND&NOT_VCN_MANAGED Uid: 10262 RequestorUid: 10262 RequestorPkg: com.mattermost.rn UnderlyingNetworks: Null] ]], android.os.BinderProxy@ee48828)
2023-02-23 13:13:35.650 1235-4487/? D/ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10262/27255, [NetworkRequest [ REQUEST id=9469, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10262 RequestorUid: 10262 RequestorPkg: com.mattermost.rn UnderlyingNetworks: Null] ]], android.os.BinderProxy@fba5941)
2023-02-23 13:13:35.651 1235-2024/? D/ConnectivityService: releasing NetworkRequest [ REQUEST id=9469, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10262 RequestorUid: 10262 RequestorPkg: com.mattermost.rn UnderlyingNetworks: Null] ] (release request)
```

**Comment by amyblais** [comment]
@dominik59 Would you be open to re-opening this issue at https://github.com/mattermost/mattermost-plugin-calls/issues?

**Comment by dominik59** [comment]
Sure, one more info is that on version 2.0.1 it's working seamlessly.

**Comment by dominik59** [comment]
https://github.com/mattermost/mattermost-plugin-calls/issues/348

**Comment by streamer45** [comment]
I was able to reproduce this but on the official build only. Building `release-2.1` locally I couldn't get it to crash. Also, it seems like it happens in DMs only.

**Comment by dominik59** [comment]
Yes i had this error on official build from Play Store
