### ISSUE TITLE
error: bundling: TypeError: Cannot read property 'tokens' of undefined

### ISSUE THREAD

**Issue by Aimn** [mattermost/mattermost-mobile#812]
Hi,I try connected http://localhost:8081/index.android.bundleplatform=android&dev=true&hot=false&minify=false

but have some error,likes that:

error: bundling: TypeError: Cannot read property 'tokens' of undefined
    at new Generator (D:\mattermost-mobile-master\node_modules\babel-generator\lib\index.js:51:21)
    at exports.default (D:\mattermost-mobile-master\node_modules\babel-generator\lib\index.js:19:13)
    at Object.transform (D:/mattermost-mobile-master/node_modules/react-native/packager/transformer.js:110:20)
    at transformCode (D:/mattermost-mobile-master/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:91:31)
    at exports.transformAndExtractDependencies (D:/mattermost-mobile-master/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:148:3)
    at handle (D:\mattermost-mobile-master\node_modules\worker-farm\lib\child\index.js:44:8)
    at process.<anonymous> (D:\mattermost-mobile-master\node_modules\worker-farm\lib\child\index.js:51:3)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:194:7)
TransformError: D:\mattermost-mobile-master\node_modules\intl\lib\core.js: Cannot read property 'tokens' of undefined

**Comment by melissanoelle** [comment]
But wait! I'm getting this same error--how did you solve it?

**Comment by Aimn** [comment]
@melissanoelle just in windows,because it has error when you npm install,node_modules was not downloaded completely
